[package]
name = "trex_wager"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "trex_wager"

[dependencies]
anchor-lang = "0.30.1"

[features]
idl-build = ["anchor-lang/idl-build"]
no-entrypoint = []
